//
// Created by Lenovo on 12/10/2024.
//

#ifndef POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_L00_EX01_H
#define POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_L00_EX01_H

#endif //POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_L00_EX01_H
