//
// Created by Lenovo on 3/20/2024.
//

#ifndef POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_2_3IF_3COMPARISONS_H
#define POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_2_3IF_3COMPARISONS_H

#endif //POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_2_3IF_3COMPARISONS_H
int solution_version_2_3if_3comparisons_function(void) ;

