//
// Created by Lenovo on 3/20/2024.
//

#ifndef POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_1_3IF_6COMPARISONS_H
#define POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_1_3IF_6COMPARISONS_H

#endif //POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_1_3IF_6COMPARISONS_H

int solution_version_1_3if_6comparisons_function(void);
