//
// Created by Lenovo on 3/19/2024.
//

#ifndef POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_1_NON_NESTED_IF_H
#define POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_1_NON_NESTED_IF_H

#endif //POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_VERSION_1_NON_NESTED_IF_H
int solution_version_1_non_nested_if_function(void);

