//
// Created by Lenovo on 5/5/2024.
//

#ifndef POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_OF_MENU_WITH_CHARACTERS_AS_SELCTORS_H
#define POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_OF_MENU_WITH_CHARACTERS_AS_SELCTORS_H

#endif //POLITO_PROGRAMMING_TECHNIQUES_PROJECTS_SOLUTION_OF_MENU_WITH_CHARACTERS_AS_SELCTORS_H
int fA();
int fL();
int fT();
